/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apps_ktr_facerec_NativeClass */

#ifndef _Included_com_apps_ktr_facerec_NativeClass
#define _Included_com_apps_ktr_facerec_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apps_ktr_facerec_NativeClass
 * Method:    getIntFromNative
 * Signature: ()I
 */
JNIEXPORT jstring JNICALL Java_com_apps_ktr_facerec_NativeClass_nativeFunction
  (JNIEnv * env, jobject obj, jint function, jboolean useTrainedData, jstring externalstorage);

#ifdef __cplusplus
}
#endif
#endif
